package com.example.jobpuzzle.interview.entity;

public enum InterviewQuestionType {
    SELF_INTRO, MOTIVATION, STRENGTH_WEAKNESS, FAILURE_CONFLICT, JOB_GENERAL, GENERAL,
    COMPANY_FIT, EXPERIENCE, PROBLEM_SOLVING, SKILL, WEAKNESS_REVIEW
}
